spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.springframework.transaction: DEBUG
